plugins {
	id 'java'
	id 'groovy'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
}
java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

group = 'org.kafka-spring-demo'
version = '0.0.1-SNAPSHOT'
//noinspection GroovyUnusedAssignment


repositories {
	mavenCentral()
	maven {
		url "https://packages.confluent.io/maven/"
	}
}

ext {
	set('springModulithVersion', "2.1.1")
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.modulith:spring-modulith-bom:${springModulithVersion}"
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

dependencies {
	implementation platform('org.apache.groovy:groovy-bom:5.0.8')
	implementation 'org.apache.groovy:groovy'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-kafka'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.0'
	testImplementation 'org.spockframework:spock-core'
	compileOnly 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	annotationProcessor 'org.projectlombok:lombok'
	implementation("io.confluent:kafka-avro-serializer:8.3.1")
	implementation("io.confluent:kafka-json-schema-serializer:8.3.1")
	testImplementation platform("org.spockframework:spock-bom:2.4-groovy-5.0")
	testImplementation "org.spockframework:spock-core"
	testImplementation "org.spockframework:spock-spring"
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testImplementation 'org.springframework.kafka:spring-kafka-test'
}

tasks.named('test') {
	useJUnitPlatform()
}
